runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main4:app

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

runtime_config:
  operating_system: ubuntu22
  runtime_version: 3.11

manual_scaling:
  instances: 5
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10